FROM --platform=$BUILDPLATFORM golang:1.20@sha256:8114f4a1bfba75e753d87fbad6a9f23d09746890df3e7749dc82bf5049d4f5fa as build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM alpine:3.17@sha256:ff6bdca1701f3a8a67e328815ff2346b0e4067d32ec36b7992c1fdc001dc8517

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="drone-github-comment"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/drone-github-comment"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/drone-github-comment"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/drone-github-comment"

COPY --from=build /src/dist/drone-github-comment /bin/drone-github-comment
ENTRYPOINT ["/bin/drone-github-comment"]
