FROM arm32v7/alpine:3.14@sha256:088557f18d845a348b4039a63c1266b09dfbe45619dc259f05742d902edd5f25

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="drone-github-comment"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/drone-github-comment"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/drone-github-comment"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/drone-github-comment"

ADD release/arm/drone-github-comment /bin/
ENTRYPOINT [ "/bin/drone-github-comment" ]
