FROM arm32v7/alpine:3.13@sha256:9663906b1c3bf891618ebcac857961531357525b25493ef717bca0f86f581ad6

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="drone-github-comment"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/drone-github-comment"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/drone-github-comment"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/drone-github-comment"

ADD release/arm/drone-github-comment /bin/
ENTRYPOINT [ "/bin/drone-github-comment" ]
